### ISSUE TITLE
The bundle looks enabled, but the option to see the trace does not show up

### ISSUE THREAD

**Issue by dimkasta** [VincentChalnot/DoctrineDebugBundle#3]
I loved the idea of this bundle. TBH this should be part of the profiler itself.

However I cannot seem to make it work. 

I followed the instructions and the bundle appears in the configuration - enabled bundles.
But the show trace option never appears.

I am running 3.4.12

Thanks in advance

**Comment by VincentChalnot** [comment]
Hello, I've reproduced the bug on a symfony/standard-edition fresh install. I'm looking into it.

**Comment by VincentChalnot** [comment]
Turns out you need xdebug installed for the stack trace to appear, I completely forgot to mention this in the docs.
I'll update the template to add a warning and also update the README.

I'll also look if I can use debug_backtrace() instead.

**Comment by dimkasta** [comment]
Ah yes it did work somewhat when xdebug was enabled. But it still throwed some exceptions

**Comment by VincentChalnot** [comment]
Throwed some exceptions ? Can you give me an example ?

**Comment by dimkasta** [comment]
I will send you the exact messages later today. I do not have access to that specific project right now.
It was something coming from the template.

I use php 7.0.x on windows for that project if it makes any difference

**Comment by VincentChalnot** [comment]
I think it could come from incompatibility with earlier versions of the web profiler but if you are using Symfony 3.4 you shouldn't see any error.

I've juste updated the code in order to use debug_backtrace() instead of the xdebug function.
Can you composer update and keep me posted ?

**Comment by dimkasta** [comment]
Looks ok now. Everything works with or without xdebug

**Comment by VincentChalnot** [comment]
Perfect, thanks for reporting this bug 👍
